# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tidydots < Formula
  desc "Cross-platform dotfile management tool"
  homepage "https://github.com/AntoineGS/tidydots"
  version "0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.2/tidydots_0.2_darwin_amd64.tar.gz"
      sha256 "e6aad575fdfeb3e62dc38bbc3ba6526bf2f8bd05a288d7670c0b96be452f1331"

      define_method(:install) do
        bin.install "tidydots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.2/tidydots_0.2_darwin_arm64.tar.gz"
      sha256 "7db47ee2a61364abd279317adb4745da14d7f5c81b4a0509dbf9a22812a9dc56"

      define_method(:install) do
        bin.install "tidydots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.2/tidydots_0.2_linux_amd64.tar.gz"
      sha256 "a32d6c84eb1d5ac36f86dc385957bc10492553c774731151a9acd8a3423f2063"
      define_method(:install) do
        bin.install "tidydots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.2/tidydots_0.2_linux_arm64.tar.gz"
      sha256 "647a4d5b61a7c21cede5c8a06320a12ad878be840344b3d85ba39f7cc8d21352"
      define_method(:install) do
        bin.install "tidydots"
      end
    end
  end
end
