# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tidydots < Formula
  desc "Cross-platform dotfile management tool"
  homepage "https://github.com/AntoineGS/tidydots"
  version "0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.4/tidydots_0.4_darwin_amd64.tar.gz"
      sha256 "940c48cb4ef3966beec3bd28d99101dba39d59362446394d025d1b8896115f36"

      define_method(:install) do
        bin.install "tidydots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.4/tidydots_0.4_darwin_arm64.tar.gz"
      sha256 "868c0d14bf51e66a33d9003d22d436ad7448bbe69f0723a09b6e8c74e31386b2"

      define_method(:install) do
        bin.install "tidydots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.4/tidydots_0.4_linux_amd64.tar.gz"
      sha256 "0d1273accf770aa04f615d3bb61e23c3d850047a122ad48c4d448d418d62162b"
      define_method(:install) do
        bin.install "tidydots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AntoineGS/tidydots/releases/download/v0.4/tidydots_0.4_linux_arm64.tar.gz"
      sha256 "ed483379072a3ff1250cd6651aaac269d7936138d59e17c570c2021a37dcd1dd"
      define_method(:install) do
        bin.install "tidydots"
      end
    end
  end
end
