# This file was generated by GoReleaser. DO NOT EDIT.
cask "tidydots" do
  version "1.0"

  on_macos do
    on_intel do
      sha256 "24b8aa2bf4ec355ea640fd06cdea42ff27c54f142dd9d9959822cb04b5a57f95"
      url "https://github.com/AntoineGS/tidydots/releases/download/v#{version}/tidydots_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e01978407039eceaed23ee3b42e7233dcf43801f88b09c2f5851019e023c1f4c"
      url "https://github.com/AntoineGS/tidydots/releases/download/v#{version}/tidydots_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e2e9c9756a956e588f601cfefbd617d693efa6f5fc91f98243ec09b98c8eaa36"
      url "https://github.com/AntoineGS/tidydots/releases/download/v#{version}/tidydots_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ec657d7429e60171bbb70e7fe3a8569ac0416a187dd1939cfa0769734a0815c"
      url "https://github.com/AntoineGS/tidydots/releases/download/v#{version}/tidydots_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tidydots"
  desc "Cross-platform dotfile management tool"
  homepage "https://github.com/AntoineGS/tidydots"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tidydots"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tidydots"]
    end
  end

  # No zap stanza required

end
